In [1]:
import deepchem as dc
import numpy as np
import pandas as pd

print("deepchem:", dc.__version__)

No normalization for SPS. Feature removed!
No normalization for AvgIpc. Feature removed!
No normalization for NumAmideBonds. Feature removed!
No normalization for NumAtomStereoCenters. Feature removed!
No normalization for NumBridgeheadAtoms. Feature removed!
No normalization for NumHeterocycles. Feature removed!
No normalization for NumSpiroAtoms. Feature removed!
No normalization for NumUnspecifiedAtomStereoCenters. Feature removed!
No normalization for Phi. Feature removed!
Skipped loading some Tensorflow models, missing a dependency. No module named 'tensorflow'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'torch_geometric'
Skipped loading modules with transformers dependency. No module named 'transformers'
cannot import name 'HuggingFaceModel' from 'deepchem.models.torch_models' (/Users/reid/py/deepchemBenchmark/.venv/lib/python3.13/site-packages/deepchem/models/torch_models/__init__.py)
Skipped loading modules with pytorch-geometric dependency, missing a dependency. cannot import name 'DMPNN' from 'deepchem.models.torch_models' (/Users/reid/py/deepchemBenchmark/.venv/lib/python3.13/site-packages/deepchem/models/torch_models/__init__.py)
Skipped loading some Jax models, missing a dependency. No module named 'jax'
Skipped loading some PyTorch models, missing a dependency. No module named 'tensorflow'

deepchem: 2.8.0

## Load ChEMBL from MoleculeNet

DeepChem exposes `load_chembl` (older ChEMBL snapshot, multitask regression on bioactivity)
and `load_chembl25` (ChEMBL v25). We use a cheap featurizer (`CircularFingerprint`) here so
loading is fast; swap in a heavier featurizer once the schema is understood.

`featurizer="ECFP"` is a shorthand accepted by most molnet loaders and is equivalent to
`dc.feat.CircularFingerprint(size=1024)`.

In [2]:
tasks, datasets, transformers = dc.molnet.load_chembl(
    featurizer="ECFP",
    set_name="sparse",   # "sparse" (multitask, mostly-missing labels) or "5thresh"
    split="random",
    reload=True,         # cache to ~/.deepchem
)
train, valid, test = datasets
print("tasks:", len(tasks))
print("train / valid / test sizes:", len(train), len(valid), len(test))

'split' is deprecated.  Use 'splitter' instead.
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:45] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator
[17:07:46] DEPRECATION WARNING: please use MorganGenerator

tasks: 691
train / valid / test sizes: 19096 2387 2388

## Dataset shape at a glance

- `X` — featurized inputs, shape `(n_samples, feature_dim)`
- `y` — labels, shape `(n_samples, n_tasks)`
- `w` — per-sample-per-task weights; `w == 0` marks *missing* labels (crucial for ChEMBL, which is very sparse)
- `ids` — one string per sample (SMILES for ChEMBL loaders)

In [3]:
print("X    :", train.X.shape, train.X.dtype)
print("y    :", train.y.shape, train.y.dtype)
print("w    :", train.w.shape, train.w.dtype)
print("ids  :", train.ids.shape, train.ids.dtype)
print("first id (SMILES?):", train.ids[0])

X    : (19096, 1024) float64
y    : (19096, 691) float64
w    : (19096, 691) float64
ids  : (19096,) object
first id (SMILES?): Cc1cccc(N2CCN(CCCCNC(=O)c3oc4ccccc4c3)CC2)c1C

In [4]:
# Task names — each column of y corresponds to one bioactivity target
print("first 10 tasks:", tasks[:10])
print("total tasks   :", len(tasks))

first 10 tasks: ['CHEMBL1075051', 'CHEMBL1075104', 'CHEMBL1075145', 'CHEMBL1075189', 'CHEMBL1075228', 'CHEMBL1075284', 'CHEMBL1075319', 'CHEMBL1163101', 'CHEMBL1163116', 'CHEMBL1163125']
total tasks   : 691

## Label sparsity

ChEMBL is a highly-sparse multitask problem: most (molecule, task) pairs have no measurement.
DeepChem encodes "no measurement" as `w == 0` (the `y` entry is a placeholder). Never trust
`y` without also checking `w`.

In [5]:
w = train.w
observed_mask = (w != 0)

n_cells = w.size
n_observed = int(observed_mask.sum())
print(f"observed labels: {n_observed:,} / {n_cells:,} ({100*n_observed/n_cells:.2f}%)")

# Per-task counts
per_task_obs = observed_mask.sum(axis=0)
print(f"labels per task -- min={per_task_obs.min()}, "
      f"median={int(np.median(per_task_obs))}, max={per_task_obs.max()}")

# Per-molecule counts
per_mol_obs = observed_mask.sum(axis=1)
print(f"tasks measured per molecule -- min={per_mol_obs.min()}, "
      f"median={int(np.median(per_mol_obs))}, max={per_mol_obs.max()}")

observed labels: 72,847 / 13,195,336 (0.55%)
labels per task -- min=0, median=31, max=1739
tasks measured per molecule -- min=3, median=3, max=97

In [6]:
# Distribution of observed y values (pooled across tasks).
# Note: `transformers` were fit on train, so these values are normalized.
observed_y = train.y[observed_mask]
print("observed y (normalized):",
      f"min={observed_y.min():.3f}",
      f"mean={observed_y.mean():.3f}",
      f"std={observed_y.std():.3f}",
      f"max={observed_y.max():.3f}")
print("transformers applied:", [type(t).__name__ for t in transformers])

observed y (normalized): min=1.632 mean=9.389 std=8.382 max=138.185
transformers applied: ['NormalizationTransformer']

## SMILES + IDs

For molnet loaders that start from SMILES (ChEMBL included), `dataset.ids` holds the SMILES
string per sample. There is no separate ChEMBL-ID column exposed by the loader — if you need
`CHEMBL####` IDs you have to cross-reference the raw ChEMBL release yourself.

In [7]:
sample = pd.DataFrame({
    "smiles": train.ids[:10],
    "n_observed_tasks": per_mol_obs[:10],
})
sample

                                              smiles  n_observed_tasks
0      Cc1cccc(N2CCN(CCCCNC(=O)c3oc4ccccc4c3)CC2)c1C                 5
1  OC(=O)c1cccc(O)c1C(=O)c2c(O)cc(cc2O)C(=O)OC3CN...                 4
2  CC(=O)OC[C@H]1O[C@@H](SCc2cn(nn2)c3ccc(cc3)S(=...                 4
3                                         CCCC(=O)NO                 5
4  COc1ccc(CC(=O)N2CCC3(CC2)CN(C3)[C@@H]4CCc5cc(c...                 3
5  CNc1ncc2cc(ccc2n1)c3cc(Nc4nc5cc(ccc5[nH]4)C(F)...                 3
6  NC(=O)c1ccc(Oc2ccc(CN3CCC[C@H]3c4cccnc4)cc2)c(...                 3
7  O=C(NCCCN1CCC2(CC1)CCc3ccccc23)[C@H]4CCCN4Cc5c...                 3
8  CC1(C)Oc2cc(cc(O)c2[C@@H]3C[C@H](O)CC[C@@H]13)...                 3
9   Cc1cccc(c1)N2CCN(CC2)C(=O)Nc3ccc(OS(=O)(=O)N)cc3                 4

In [8]:
# Sanity-check that ids are valid SMILES by round-tripping through RDKit.
from rdkit import Chem
bad = [s for s in train.ids[:200] if Chem.MolFromSmiles(s) is None]
print(f"invalid SMILES in first 200 ids: {len(bad)}")

invalid SMILES in first 200 ids: 0

## Peek at a single task

Pick the task with the most observations and look at its label distribution + a few example
molecules.

In [9]:
top_task_idx = int(per_task_obs.argmax())
top_task = tasks[top_task_idx]
mask = observed_mask[:, top_task_idx]
print(f"task: {top_task}  (idx={top_task_idx}, n_observed={mask.sum()})")

y_task = train.y[mask, top_task_idx]
print(f"y stats: min={y_task.min():.3f}  mean={y_task.mean():.3f}  max={y_task.max():.3f}")

pd.DataFrame({
    "smiles": train.ids[mask][:10],
    "y_normalized": y_task[:10],
})

task: CHEMBL261  (idx=237, n_observed=1739)
y stats: min=1.854  mean=3.103  max=5.642

                                              smiles  y_normalized
0  CC(=O)OC[C@H]1O[C@@H](SCc2cn(nn2)c3ccc(cc3)S(=...      3.499020
1   Cc1cccc(c1)N2CCN(CC2)C(=O)Nc3ccc(OS(=O)(=O)N)cc3      2.974076
2           CC(C)(C)OC(=O)NCCCCOc1ccc(cc1)S(=O)(=O)N      3.688433
3  COc1ccc(\C=C(/C#N)\C(=O)Nc2ccc(cc2)S(=O)(=O)N)cc1      3.693845
4                         COc1cc2C=CC(=O)Oc2c(O)c1OC      2.395014
5                  NC(=O)CN1C=CC(=O)C(=C1)S(=O)(=O)N      2.519485
6             NS(=O)(=O)c1ccc(OCCCCO[N+](=O)[O-])cc1      3.688433
7  NS(=O)(=O)c1ccc(N2C(=O)c3c(Cl)c(Cl)c(Cl)c(Cl)c...      3.168900
8      Cc1cc(C)nc(Sc2c(F)c(F)c(c(F)c2F)S(=O)(=O)N)n1      4.343260
9  CCCN(C)c1nc(NCCc2ccc(cc2)S(=O)(=O)N)nc(n1)N(C)CCC      3.315019

In [10]:
# Optional: un-transform y back to the original label scale for that one task.
y_task_col = np.zeros_like(train.y)
y_task_col[mask, top_task_idx] = y_task
w_task_col = np.zeros_like(train.w)
w_task_col[mask, top_task_idx] = 1.0

restored = train.y.copy()
for t in reversed(transformers):
    restored = t.untransform(restored)
print("untransformed y range for top task:",
      restored[mask, top_task_idx].min(),
      restored[mask, top_task_idx].max())

untransformed y range for top task: 4.0 11.0

In [11]:
train.get_statistics()

(array([0.01838081, 0.27906368, 0.06200251, ..., 0.02576456, 0.0164956 ,
        0.00858819], shape=(1024,)),
 array([0.13432408, 0.4485389 , 0.24116012, ..., 0.15843215, 0.12737149,
        0.09227366], shape=(1024,)),
 array([-7.65082510e-19, -3.83705925e-19,  0.00000000e+00,  0.00000000e+00,
        -1.07959855e-16, -1.61276132e-16,  6.11187211e-17, -8.41878752e-17,
         0.00000000e+00,  4.49730026e-17, -4.21229485e-18,  0.00000000e+00,
        -2.13186546e-17, -5.97158228e-20, -1.13886227e-17, -3.54534110e-17,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  6.20753389e-17,
        -2.24829014e-17,  1.54730685e-16,  0.00000000e+00, -2.24780945e-16,
         4.17582161e-16,  1.72792921e-16,  3.77937631e-17, -5.38665309e-18,
         3.67679215e-16, -2.66874671e-16, -3.02136652e-18,  1.86981253e-16,
        -3.45583513e-16,  0.00000000e+00, -1.75712750e-16,  0.00000000e+00,
        -9.74858689e-17,  8.02936412e-17, -8.28872561e-17,  4.50099332e-16,
        -2.69889261e-16, -2.91478860e-17,  3.11508225e-16,  8.71961127e-17,
        -7.29828998e-17, -2.31748214e-17,  8.70891748e-17,  4.32089294e-16,
        -2.87345763e-16, -6.29835912e-16,  1.59816482e-16, -2.16756578e-16,
         3.31329643e-17, -8.33268662e-17,  0.00000000e+00, -2.13263414e-16,
         2.92717646e-17,  0.00000000e+00, -4.76782988e-16,  6.91360997e-17,
        -5.90233733e-18, -1.86713167e-16,  3.06347465e-17, -6.89649990e-17,
        -2.61036496e-17,  2.89006795e-16,  3.64451172e-16, -4.52514647e-16,
         5.29412533e-16, -1.29266122e-16,  0.00000000e+00,  4.08798853e-16,
        -5.88391437e-17, -3.70863212e-16,  2.22242811e-16, -2.24107130e-16,
        -2.22191989e-16,  7.26606038e-16, -4.33853452e-17, -8.21215383e-17,
        -1.51513018e-19,  3.57501902e-17, -5.47541155e-17, -1.13982683e-16,
        -1.20627656e-16,  9.06198199e-18,  2.97454254e-16, -5.56819872e-17,
        -1.38570355e-17,  5.73585301e-17,  9.17878783e-17,  5.46200726e-16,
        -2.31056188e-16, -6.14437700e-17,  4.54044388e-16, -1.38465535e-17,
        -4.46142841e-16,  3.46282315e-16, -3.07810714e-16, -3.63850943e-17,
        -1.46495195e-16,  0.00000000e+00,  0.00000000e+00, -6.48623950e-17,
        -7.16234967e-16, -9.67438681e-18,  9.19259447e-16,  0.00000000e+00,
         2.15414031e-16, -2.12545977e-16,  4.06436901e-16,  3.23951139e-16,
        -4.06169239e-16,  8.17327502e-17, -9.15617205e-17, -2.76009498e-16,
        -4.27759262e-16, -5.14148999e-17, -2.00308045e-16,  6.16072474e-17,
         0.00000000e+00,  9.08082847e-17, -3.01224398e-16, -1.79596396e-17,
        -7.42318499e-18, -2.62508216e-16, -1.33356867e-17,  0.00000000e+00,
         0.00000000e+00,  5.55319882e-16,  1.24467256e-16,  1.75398501e-16,
         0.00000000e+00, -8.15826559e-16, -3.73329772e-16,  1.01473277e-16,
         3.72293003e-16,  1.83695188e-15, -7.01273400e-17,  3.53593057e-16,
         2.62666611e-16,  9.21436321e-17, -1.12686722e-16,  0.00000000e+00,
        -2.54016711e-17,  1.91250722e-16, -1.34041270e-16, -9.69404644e-16,
         1.03687505e-15, -8.56058083e-17, -2.44723065e-16,  8.46145257e-16,
         2.07941295e-16,  1.90910638e-17,  1.68748445e-16,  5.39462579e-17,
        -1.32530841e-15, -1.57080142e-16, -3.68624503e-17, -9.73123966e-16,
        -4.41524394e-17,  2.13096125e-16, -7.55138343e-17,  1.15446991e-16,
         7.59471763e-16,  5.17863238e-17,  5.90546289e-16,  5.90887643e-16,
         5.90782187e-17, -1.27795461e-16,  1.20165176e-16, -5.67850888e-18,
        -1.20514577e-16, -6.53867084e-18, -1.94119623e-16, -9.86738326e-17,
         3.99000799e-16, -8.99305044e-16,  0.00000000e+00,  3.11800451e-16,
        -2.98362062e-17,  1.74632783e-17,  0.00000000e+00,  5.13810186e-18,
        -6.27895995e-17,  2.34307948e-16,  3.37271579e-17, -7.99106129e-16,
         7.57286418e-16,  1.18289422e-16, -2.08579110e-16, -1.83428373e-16,
         1.18505415e-16,  3.42669720e-16, -9.62792705e-17,  5.15912945e-17,
         4.46859431e-16,  9.06142294e-16,  4.85043888e-17, -4.32522551e-16,
         5.35091889e-17, -4.70540355e-16,  0.00000000e+00, -2.76131047e-16,
        -2.84175319e-16,  3.15336602e-17,  4.33812159e-17,  2.78278275e-16,
         2.11167431e-17, -1.84225854e-16,  1.03196565e-16, -3.50053306e-17,
        -2.05204319e-16,  3.96830701e-16, -3.06611104e-17,  2.84302797e-16,
        -3.10385059e-16,  0.00000000e+00, -3.57172618e-17, -6.97116586e-17,
        -1.57213550e-16,  1.28964790e-16, -1.35167612e-16,  5.63261663e-16,
        -3.00849162e-16,  1.16898170e-15,  1.57350770e-16, -1.84665888e-17,
        -1.67723641e-17, -6.25401483e-18, -1.05882930e-16, -6.46698644e-16,
        -5.51941068e-16, -6.50773719e-16, -5.52961107e-17, -2.04632149e-16,
         1.60250163e-17, -2.20631076e-15,  0.00000000e+00,  6.07100277e-18,
         2.51997384e-16,  1.03529025e-16,  2.33171230e-17,  2.98870493e-16,
        -2.05207284e-16,  6.36253033e-17,  0.00000000e+00, -2.83764508e-17,
        -9.94647920e-16,  7.82577128e-16, -2.51192914e-17, -2.70871396e-16,
        -7.47557398e-17, -2.91904071e-16,  8.16285651e-18, -4.88664319e-16,
         0.00000000e+00,  4.32073624e-17, -8.59281044e-17,  5.72482464e-16,
        -2.02327795e-16, -3.67821516e-16,  1.57657925e-16,  2.85280697e-17,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.33056382e-16,
         9.88595446e-17, -6.34918957e-16, -2.27277574e-16,  8.91633467e-17,
         6.08281888e-17, -4.85201648e-17, -3.03739662e-16,  3.16282103e-16,
        -3.07793138e-16, -1.37941433e-17,  2.13451456e-16,  2.55764140e-16,
        -1.18692186e-16, -8.55299989e-17, -3.47384094e-17, -2.27135696e-16,
         1.04242863e-16, -2.01224112e-16, -8.15834606e-17, -9.42786846e-17,
         1.60859180e-16, -2.36202337e-16, -1.30580717e-16, -2.28872538e-17,
        -9.85184021e-17,  4.41027821e-17,  3.81274941e-17,  9.28212585e-17,
         2.37614341e-16,  4.11408985e-16,  6.51643622e-17, -1.15308713e-16,
        -1.38644047e-16,  3.30661334e-16, -6.91225472e-17, -9.75578667e-17,
         0.00000000e+00, -3.35491539e-16, -6.94380670e-17, -7.59474304e-16,
        -7.88604615e-17,  3.82138914e-18,  4.02958137e-16,  1.25716630e-17,
         3.01797839e-16, -1.31132982e-16,  1.65613576e-16,  2.10838359e-16,
         7.88111218e-18,  2.14875847e-17,  1.34283310e-16,  9.10751001e-17,
         8.73017800e-17,  1.67335594e-17, -2.96594516e-16,  0.00000000e+00,
        -2.34026733e-17,  0.00000000e+00,  2.52858393e-17, -1.68972485e-18,
         1.71910419e-16,  1.36677660e-16,  7.07895927e-16,  2.86497036e-16,
         5.07448968e-17, -8.01392694e-17,  3.55625089e-16, -1.33483922e-16,
         0.00000000e+00,  1.19630698e-16,  1.62272031e-16, -3.90283136e-17,
         6.27122018e-17,  5.29082190e-17,  2.14869389e-16,  3.62403046e-18,
         1.60570342e-16,  4.40125096e-16, -2.09120576e-16,  4.72170046e-16,
         6.59784456e-16,  2.16199019e-16, -1.48652165e-16, -4.74241042e-17,
        -1.32996031e-16,  1.43103675e-16,  8.65384763e-16, -3.71423947e-17,
        -6.99988028e-17, -1.24945618e-16,  7.01389867e-17, -6.67846515e-16,
         3.41369524e-16, -3.85145881e-18,  1.53626366e-16,  6.02947698e-17,
         3.00669591e-16, -1.41746305e-16, -2.02951212e-17, -2.80511054e-16,
        -2.86781639e-16, -7.96797541e-17, -1.05306524e-16, -1.49435670e-17,
        -2.96673290e-17, -2.24190986e-16,  5.59677020e-18,  4.69944044e-16,
         6.70167174e-18, -2.77072947e-16, -4.33714750e-16,  0.00000000e+00,
        -3.84402610e-17, -6.14183590e-17, -3.35062941e-17,  1.47781838e-17,
        -2.14485683e-17, -3.84432256e-17,  5.58986688e-17, -1.19008129e-17,
        -9.19115451e-18,  1.47058472e-16,  1.11840960e-16, -4.09091503e-17,
         5.08219768e-17, -6.35947043e-18, -8.14670995e-17,  6.92398612e-16,
         2.52042065e-17, -2.02596728e-16,  1.34006541e-16, -7.52769827e-17,
        -1.35015358e-16, -1.35180317e-16, -6.53604503e-17,  7.62016250e-17,
         1.51910277e-16,  0.00000000e+00, -7.01309399e-17, -1.18927237e-16,
         0.00000000e+00,  0.00000000e+00,  9.06274432e-16, -3.52331825e-17,
         3.90147611e-16, -7.38142627e-17, -9.59080583e-17,  0.00000000e+00,
        -1.45255563e-18,  5.60132724e-16, -6.83750406e-17,  0.00000000e+00,
         1.00153176e-16, -3.29017243e-16, -1.49818106e-16,  7.49014295e-17,
         4.06177709e-17,  4.47322335e-17,  1.41219027e-16, -5.01746319e-17,
         1.88510994e-16,  0.00000000e+00, -1.66272991e-16,  2.87055231e-17,
        -1.44783342e-16,  5.82771373e-17, -2.37710903e-16,  2.25665459e-17,
        -4.28319150e-16, -1.96908055e-16,  0.00000000e+00,  0.00000000e+00,
         3.21523119e-16,  0.00000000e+00, -5.93394225e-17,  0.00000000e+00,
        -2.21887692e-17, -6.34347209e-17, -4.96437540e-16, -2.09871047e-16,
         0.00000000e+00,  1.07208960e-16, -1.42455060e-17,  8.02036440e-17,
         1.45710631e-16,  8.28508337e-17,  1.56201346e-17, -3.27352823e-16,
         3.30724014e-16, -3.35664334e-17, -2.96032192e-17,  1.26072384e-16,
         3.89399575e-17, -4.53849571e-16, -1.15134012e-16, -4.57575668e-17,
         0.00000000e+00,  0.00000000e+00, -4.26513276e-16,  2.20885864e-16,
         3.21334654e-17,  1.83632931e-16, -1.52461695e-16, -3.32927994e-16,
        -5.02735230e-17,  1.31325047e-17,  5.73365072e-17,  3.77424117e-17,
        -3.68721912e-17, -4.72644385e-19, -6.39513581e-17, -7.04069668e-17,
        -1.42039802e-16, -1.05060885e-16,  3.42149430e-17,  4.17121375e-17,
        -5.35618743e-16,  0.00000000e+00, -2.38071951e-16, -1.20437921e-16,
        -2.35187168e-17,  1.41696965e-17,  8.88897551e-16, -2.73535738e-16,
         0.00000000e+00,  1.08688303e-16,  2.46771191e-16,  8.84370160e-17,
        -8.16495292e-17,  2.07650127e-18,  1.31395986e-17, -1.81110891e-16,
         1.87628809e-16,  1.77349217e-16,  0.00000000e+00, -1.46178828e-16,
        -1.95943285e-16, -1.16181580e-16, -7.01913969e-17, -1.56223369e-16,
         1.33757514e-16,  0.00000000e+00, -2.03863890e-17,  7.31154605e-17,
        -1.70292374e-16, -1.34246040e-16, -1.42936810e-17,  0.00000000e+00,
         0.00000000e+00,  1.76791870e-16,  3.51704597e-16, -1.38295069e-16,
         0.00000000e+00, -2.36251042e-16, -7.46828950e-17,  1.50159460e-16,
         8.23360494e-17,  9.32824679e-17,  0.00000000e+00,  3.27672578e-16,
        -3.68116284e-17, -7.77799651e-17,  4.19433775e-17,  4.65143908e-17,
         5.48555477e-17, -1.83642672e-16,  0.00000000e+00,  6.51510214e-17,
        -1.06443242e-16,  1.28255611e-16,  8.00465193e-17,  0.00000000e+00,
         2.13935959e-16,  1.61086185e-16,  3.83223116e-17,  9.48494789e-17,
         0.00000000e+00, -4.39797294e-16,  3.91825795e-17,  5.94193612e-18,
         1.76044998e-16,  2.81723158e-18, -6.02348422e-17,  2.66037802e-16,
         6.65255442e-17,  6.57210746e-17, -5.70764681e-16, -5.84600964e-18,
         0.00000000e+00,  3.24966308e-17,  3.00484938e-17,  6.95892623e-17,
         0.00000000e+00,  0.00000000e+00, -2.09262878e-16,  1.29087821e-18,
         8.76314876e-17, -1.35216105e-17,  6.24456406e-16,  2.63267369e-17,
         2.10207955e-16, -1.15558587e-16, -3.27505289e-16, -2.44709936e-17,
        -9.39943991e-17,  1.57380416e-16,  0.00000000e+00,  0.00000000e+00,
        -4.76164653e-16,  0.00000000e+00, -2.21054847e-16, -1.54691510e-17,
        -2.87369480e-16,  8.14026191e-17,  6.55870317e-16, -4.08250822e-17,
         5.46497187e-17,  2.09644890e-17, -3.96873052e-17, -7.70766101e-17,
         3.17177416e-16,  1.21125711e-18, -6.90710899e-17,  1.15138883e-16,
         1.05794415e-16, -3.63017145e-18, -8.97594461e-17,  0.00000000e+00,
         6.49839442e-17, -1.01240237e-16, -8.80914265e-19,  4.17290781e-17,
        -6.34716727e-17, -5.25126546e-17, -1.15115589e-16,  5.17460898e-17,
         2.93363509e-17, -5.22594976e-17, -1.43241742e-17,  0.00000000e+00,
         2.21458882e-17,  0.00000000e+00, -2.88342721e-16,  1.31062043e-16,
        -3.62426340e-17,  2.89912273e-16, -1.39907079e-17,  1.21709105e-16,
        -3.40210783e-16,  0.00000000e+00, -6.66106710e-18, -1.54783413e-16,
        -1.46169299e-17,  0.00000000e+00,  9.03138292e-18,  0.00000000e+00,
        -2.13077914e-16, -4.36573487e-17, -4.08930566e-17, -9.10162313e-17,
         0.00000000e+00, -1.02667593e-16,  5.33192417e-17,  2.98364391e-16,
         3.53879777e-18,  1.08996200e-16, -6.78621622e-17,  2.30064313e-16,
        -2.05555838e-17, -6.82619617e-17,  1.97623375e-19, -1.74469729e-17,
         2.51187621e-17,  1.36833937e-16, -1.22068036e-17,  0.00000000e+00,
         2.95066045e-17,  9.38152517e-18, -2.39318995e-16,  1.06430537e-16,
         1.29528278e-16, -3.53692371e-17, -4.40500755e-16,  0.00000000e+00,
        -9.92769201e-17,  1.93876313e-17,  9.53536752e-17,  1.40287714e-17,
         0.00000000e+00, -1.39557995e-16, -2.05286905e-17,  2.97181510e-18,
         4.95700621e-17,  1.01067548e-16,  0.00000000e+00,  1.22824013e-17,
        -1.33494087e-16, -8.32463981e-18,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.27266700e-18, -4.21880853e-16,  1.81648333e-17,
         2.26695663e-17, -1.19189182e-16,  0.00000000e+00, -1.34046352e-16,
         0.00000000e+00,  2.37063346e-19,  3.33868624e-17, -6.84209921e-17,
        -4.30272620e-17, -6.85942104e-17,  2.01868068e-17,  2.02046581e-16,
        -7.17191267e-17,  1.66431386e-18,  0.00000000e+00,  1.34906938e-16,
         2.40938522e-17,  2.39793757e-16,  2.72066136e-16]),
 array([1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0.,
        0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
        1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
        0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
        0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0.,
        1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
        1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
        1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
        0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
        0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
        1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
        1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
        1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.]))

## Sample-0 JSON record

Bundle the first training sample's SMILES, its 1024-bit ECFP vector, and every observed
`y` value into a single JSON object. For each task with `w != 0` we add a top-level entry
keyed by the task name and valued by the corresponding `y`.

In [17]:
tasks[task_idx]

'CHEMBL214'

In [29]:
tasks

['CHEMBL1075051',
 'CHEMBL1075104',
 'CHEMBL1075145',
 'CHEMBL1075189',
 'CHEMBL1075228',
 'CHEMBL1075284',
 'CHEMBL1075319',
 'CHEMBL1163101',
 'CHEMBL1163116',
 'CHEMBL1163125',
 'CHEMBL1255149',
 'CHEMBL1255150',
 'CHEMBL1293255',
 'CHEMBL1293289',
 'CHEMBL1293292',
 'CHEMBL1741186',
 'CHEMBL1741195',
 'CHEMBL1744525',
 'CHEMBL1764940',
 'CHEMBL1781',
 'CHEMBL1781862',
 'CHEMBL1782',
 'CHEMBL1784',
 'CHEMBL1790',
 'CHEMBL1792',
 'CHEMBL1795101',
 'CHEMBL1795126',
 'CHEMBL1800',
 'CHEMBL1801',
 'CHEMBL1804',
 'CHEMBL1806',
 'CHEMBL1811',
 'CHEMBL1821',
 'CHEMBL1822',
 'CHEMBL1824',
 'CHEMBL1825',
 'CHEMBL1827',
 'CHEMBL1829',
 'CHEMBL1833',
 'CHEMBL1836',
 'CHEMBL1844',
 'CHEMBL1849',
 'CHEMBL1850',
 'CHEMBL1853',
 'CHEMBL1855',
 'CHEMBL1856',
 'CHEMBL1860',
 'CHEMBL1862',
 'CHEMBL1865',
 'CHEMBL1867',
 'CHEMBL1868',
 'CHEMBL1871',
 'CHEMBL1873',
 'CHEMBL1875',
 'CHEMBL1878',
 'CHEMBL1881',
 'CHEMBL1889',
 'CHEMBL1892',
 'CHEMBL1898',
 'CHEMBL1899',
 'CHEMBL1900',
 'CHEMBL1901',
 'CHEMBL1902',
 'CHEMBL1906',
 'CHEMBL1907',
 'CHEMBL1908',
 'CHEMBL1913',
 'CHEMBL1914',
 'CHEMBL1916',
 'CHEMBL1917',
 'CHEMBL1919',
 'CHEMBL1921',
 'CHEMBL1921666',
 'CHEMBL1926',
 'CHEMBL1936',
 'CHEMBL1937',
 'CHEMBL1941',
 'CHEMBL1942',
 'CHEMBL1944',
 'CHEMBL1945',
 'CHEMBL1946',
 'CHEMBL1947',
 'CHEMBL1949',
 'CHEMBL1951',
 'CHEMBL1952',
 'CHEMBL1955',
 'CHEMBL1957',
 'CHEMBL1966',
 'CHEMBL1968',
 'CHEMBL1974',
 'CHEMBL1977',
 'CHEMBL1978',
 'CHEMBL1980',
 'CHEMBL1981',
 'CHEMBL1983',
 'CHEMBL1985',
 'CHEMBL1991',
 'CHEMBL1994',
 'CHEMBL1995',
 'CHEMBL1997',
 'CHEMBL2000',
 'CHEMBL2001',
 'CHEMBL2002',
 'CHEMBL2007',
 'CHEMBL2014',
 'CHEMBL2016',
 'CHEMBL202',
 'CHEMBL2027',
 'CHEMBL2028',
 'CHEMBL203',
 'CHEMBL2034',
 'CHEMBL2035',
 'CHEMBL2039',
 'CHEMBL204',
 'CHEMBL2041',
 'CHEMBL2047',
 'CHEMBL2049',
 'CHEMBL205',
 'CHEMBL2056',
 'CHEMBL206',
 'CHEMBL2061',
 'CHEMBL2069',
 'CHEMBL208',
 'CHEMBL2083',
 'CHEMBL2085',
 'CHEMBL209',
 'CHEMBL210',
 'CHEMBL2107',
 'CHEMBL2108',
 'CHEMBL211',
 'CHEMBL213',
 'CHEMBL214',
 'CHEMBL2146302',
 'CHEMBL2147',
 'CHEMBL2148',
 'CHEMBL215',
 'CHEMBL216',
 'CHEMBL217',
 'CHEMBL2179',
 'CHEMBL218',
 'CHEMBL2185',
 'CHEMBL219',
 'CHEMBL220',
 'CHEMBL2207',
 'CHEMBL2208',
 'CHEMBL221',
 'CHEMBL222',
 'CHEMBL223',
 'CHEMBL224',
 'CHEMBL2243',
 'CHEMBL225',
 'CHEMBL226',
 'CHEMBL2265',
 'CHEMBL227',
 'CHEMBL2274',
 'CHEMBL2276',
 'CHEMBL228',
 'CHEMBL2285',
 'CHEMBL2288',
 'CHEMBL229',
 'CHEMBL2292',
 'CHEMBL230',
 'CHEMBL2304402',
 'CHEMBL2304404',
 'CHEMBL231',
 'CHEMBL2318',
 'CHEMBL232',
 'CHEMBL2326',
 'CHEMBL2327',
 'CHEMBL2329',
 'CHEMBL233',
 'CHEMBL2334',
 'CHEMBL2335',
 'CHEMBL2337',
 'CHEMBL234',
 'CHEMBL2345',
 'CHEMBL235',
 'CHEMBL236',
 'CHEMBL2361',
 'CHEMBL2363',
 'CHEMBL2366456',
 'CHEMBL2366505',
 'CHEMBL2366512',
 'CHEMBL2366516',
 'CHEMBL2366517',
 'CHEMBL237',
 'CHEMBL2373',
 'CHEMBL238',
 'CHEMBL239',
 'CHEMBL2391',
 'CHEMBL2397',
 'CHEMBL240',
 'CHEMBL2409',
 'CHEMBL241',
 'CHEMBL2413',
 'CHEMBL2414',
 'CHEMBL242',
 'CHEMBL2425',
 'CHEMBL243',
 'CHEMBL2431',
 'CHEMBL2434',
 'CHEMBL244',
 'CHEMBL2447',
 'CHEMBL245',
 'CHEMBL246',
 'CHEMBL2461',
 'CHEMBL247',
 'CHEMBL2470',
 'CHEMBL2474',
 'CHEMBL248',
 'CHEMBL2487',
 'CHEMBL2488',
 'CHEMBL2489',
 'CHEMBL249',
 'CHEMBL2492',
 'CHEMBL2499',
 'CHEMBL251',
 'CHEMBL252',
 'CHEMBL2525',
 'CHEMBL2527',
 'CHEMBL253',
 'CHEMBL2534',
 'CHEMBL2536',
 'CHEMBL254',
 'CHEMBL255',
 'CHEMBL256',
 'CHEMBL2563',
 'CHEMBL2564',
 'CHEMBL2567',
 'CHEMBL2568',
 'CHEMBL2575',
 'CHEMBL258',
 'CHEMBL2581',
 'CHEMBL259',
 'CHEMBL2590',
 'CHEMBL2599',
 'CHEMBL260',
 'CHEMBL261',
 'CHEMBL2611',
 'CHEMBL2617',
 'CHEMBL262',
 'CHEMBL2622',
 'CHEMBL2637',
 'CHEMBL264',
 'CHEMBL265',
 'CHEMBL2652',
 'CHEMBL2664',
 'CHEMBL267',
 'CHEMBL268',
 'CHEMBL269',
 'CHEMBL2693',
 'CHEMBL2695',
 'CHEMBL270',
 'CHEMBL2716',
 'CHEMBL2722',
 'CHEMBL273',
 'CHEMBL2730',
 'CHEMBL2736',
 'CHEMBL274',
 'CHEMBL2742',
 'CHEMBL2749',
 'CHEMBL275',
 'CHEMBL2756',
 'CHEMBL276',
 'CHEMBL2778',
 'CHEMBL278',
 'CHEMBL2781',
 'CHEMBL2782',
 'CHEMBL2789',
 'CHEMBL279',
 'CHEMBL280',
 'CHEMBL2803',
 'CHEMBL2808',
 'CHEMBL2815',
 'CHEMBL2820',
 'CHEMBL2828',
 'CHEMBL283',
 'CHEMBL2830',
 'CHEMBL2835',
 'CHEMBL284',
 'CHEMBL2842',
 'CHEMBL285',
 'CHEMBL2851',
 'CHEMBL2858',
 'CHEMBL286',
 'CHEMBL2868',
 'CHEMBL287',
 'CHEMBL2871',
 'CHEMBL288',
 'CHEMBL2882',
 'CHEMBL2885',
 'CHEMBL2902',
 'CHEMBL2903',
 'CHEMBL2916',
 'CHEMBL2949',
 'CHEMBL2954',
 'CHEMBL2959',
 'CHEMBL2971',
 'CHEMBL2973',
 'CHEMBL2978',
 'CHEMBL298',
 'CHEMBL299',
 'CHEMBL2993',
 'CHEMBL2996',
 'CHEMBL2998',
 'CHEMBL301',
 'CHEMBL3012',
 'CHEMBL3018',
 'CHEMBL302',
 'CHEMBL3024',
 'CHEMBL3025',
 'CHEMBL3037',
 'CHEMBL304',
 'CHEMBL3045',
 'CHEMBL3048',
 'CHEMBL3060',
 'CHEMBL3066',
 'CHEMBL3067',
 'CHEMBL3072',
 'CHEMBL308',
 'CHEMBL3081',
 'CHEMBL3085613',
 'CHEMBL309',
 'CHEMBL3100',
 'CHEMBL3105',
 'CHEMBL3106',
 'CHEMBL311',
 'CHEMBL3114',
 'CHEMBL3116',
 'CHEMBL312',
 'CHEMBL313',
 'CHEMBL3130',
 'CHEMBL3138',
 'CHEMBL3142',
 'CHEMBL3145',
 'CHEMBL3155',
 'CHEMBL3157',
 'CHEMBL3166',
 'CHEMBL318',
 'CHEMBL3180',
 'CHEMBL3181',
 'CHEMBL319',
 'CHEMBL3192',
 'CHEMBL3199',
 'CHEMBL3202',
 'CHEMBL321',
 'CHEMBL322',
 'CHEMBL3222',
 'CHEMBL3223',
 'CHEMBL3227',
 'CHEMBL3229',
 'CHEMBL3230',
 'CHEMBL3231',
 'CHEMBL324',
 'CHEMBL3242',
 'CHEMBL3247',
 'CHEMBL325',
 'CHEMBL3254',
 'CHEMBL326',
 'CHEMBL3267',
 'CHEMBL3286',
 'CHEMBL330',
 'CHEMBL3305',
 'CHEMBL331',
 'CHEMBL3310',
 'CHEMBL3314',
 'CHEMBL3318',
 'CHEMBL332',
 'CHEMBL333',
 'CHEMBL3332',
 'CHEMBL335',
 'CHEMBL3351',
 'CHEMBL3358',
 'CHEMBL3360',
 'CHEMBL3361',
 'CHEMBL3371',
 'CHEMBL3374',
 'CHEMBL338',
 'CHEMBL339',
 'CHEMBL3399910',
 'CHEMBL340',
 'CHEMBL3403',
 'CHEMBL3419',
 'CHEMBL3426',
 'CHEMBL3437',
 'CHEMBL3438',
 'CHEMBL344',
 'CHEMBL3464',
 'CHEMBL3468',
 'CHEMBL3471',
 'CHEMBL3473',
 'CHEMBL3474',
 'CHEMBL3476',
 'CHEMBL3486',
 'CHEMBL3501',
 'CHEMBL3510',
 'CHEMBL3513',
 'CHEMBL3522',
 'CHEMBL3524',
 'CHEMBL3535',
 'CHEMBL3553',
 'CHEMBL3559',
 'CHEMBL3563',
 'CHEMBL3568',
 'CHEMBL3571',
 'CHEMBL3572',
 'CHEMBL3582',
 'CHEMBL3587',
 'CHEMBL3589',
 'CHEMBL3590',
 'CHEMBL3594',
 'CHEMBL3602',
 'CHEMBL3614',
 'CHEMBL3623',
 'CHEMBL3629',
 'CHEMBL3638338',
 'CHEMBL3649',
 'CHEMBL3650',
 'CHEMBL3687',
 'CHEMBL3691',
 'CHEMBL3699',
 'CHEMBL3706',
 'CHEMBL3710',
 'CHEMBL3717',
 'CHEMBL3729',
 'CHEMBL3746',
 'CHEMBL3759',
 'CHEMBL3764',
 'CHEMBL3766',
 'CHEMBL3768',
 'CHEMBL3769',
 'CHEMBL3772',
 'CHEMBL3775',
 'CHEMBL3776',
 'CHEMBL3778',
 'CHEMBL3785',
 'CHEMBL3788',
 'CHEMBL3795',
 'CHEMBL3798',
 'CHEMBL3802',
 'CHEMBL3807',
 'CHEMBL3815',
 'CHEMBL3816',
 'CHEMBL3820',
 'CHEMBL3833',
 'CHEMBL3836',
 'CHEMBL3837',
 'CHEMBL3864',
 'CHEMBL3868',
 'CHEMBL3869',
 'CHEMBL3880',
 'CHEMBL3884',
 'CHEMBL3891',
 'CHEMBL3892',
 'CHEMBL3910',
 'CHEMBL3912',
 'CHEMBL3920',
 'CHEMBL3922',
 'CHEMBL3942',
 'CHEMBL3943',
 'CHEMBL3948',
 'CHEMBL3952',
 'CHEMBL3959',
 'CHEMBL3969',
 'CHEMBL3974',
 'CHEMBL3975',
 'CHEMBL3976',
 'CHEMBL3979',
 'CHEMBL3983',
 'CHEMBL3991',
 'CHEMBL3996',
 'CHEMBL4005',
 'CHEMBL4015',
 'CHEMBL4016',
 'CHEMBL4018',
 'CHEMBL4026',
 'CHEMBL4029',
 'CHEMBL4040',
 'CHEMBL4051',
 'CHEMBL4068',
 'CHEMBL4072',
 'CHEMBL4073',
 'CHEMBL4074',
 'CHEMBL4077',
 'CHEMBL4078',
 'CHEMBL4080',
 'CHEMBL4093',
 'CHEMBL4102',
 'CHEMBL4111',
 'CHEMBL4123',
 'CHEMBL4124',
 'CHEMBL4128',
 'CHEMBL4132',
 'CHEMBL4140',
 'CHEMBL4142',
 'CHEMBL4145',
 'CHEMBL4150',
 'CHEMBL4153',
 'CHEMBL4161',
 'CHEMBL4179',
 'CHEMBL4188',
 'CHEMBL4191',
 'CHEMBL4198',
 'CHEMBL4203',
 'CHEMBL4204',
 'CHEMBL4224',
 'CHEMBL4234',
 'CHEMBL4235',
 'CHEMBL4247',
 'CHEMBL4261',
 'CHEMBL4282',
 'CHEMBL4296',
 'CHEMBL4302',
 'CHEMBL4303',
 'CHEMBL4306',
 'CHEMBL4308',
 'CHEMBL4315',
 'CHEMBL4321',
 'CHEMBL4333',
 'CHEMBL4336',
 'CHEMBL4338',
 'CHEMBL4354',
 'CHEMBL4358',
 'CHEMBL4361',
 'CHEMBL4372',
 'CHEMBL4393',
 'CHEMBL4394',
 'CHEMBL4409',
 'CHEMBL4414',
 'CHEMBL4422',
 'CHEMBL4427',
 'CHEMBL4429',
 'CHEMBL4430',
 'CHEMBL4439',
 'CHEMBL4441',
 'CHEMBL4462',
 'CHEMBL4465',
 'CHEMBL4471',
 'CHEMBL4477',
 'CHEMBL4478',
 'CHEMBL4481',
 'CHEMBL4482',
 'CHEMBL4501',
 'CHEMBL4506',
 'CHEMBL4508',
 'CHEMBL4523',
 'CHEMBL4550',
 'CHEMBL4552',
 'CHEMBL4561',
 'CHEMBL4581',
 'CHEMBL4586',
 'CHEMBL4588',
 'CHEMBL4599',
 'CHEMBL4600',
 'CHEMBL4608',
 'CHEMBL4616',
 'CHEMBL4617',
 'CHEMBL4618',
 'CHEMBL4625',
 'CHEMBL4630',
 'CHEMBL4633',
 'CHEMBL4641',
 'CHEMBL4644',
 'CHEMBL4649',
 'CHEMBL4652',
 'CHEMBL4653',
 'CHEMBL4657',
 'CHEMBL4660',
 'CHEMBL4662',
 'CHEMBL4681',
 'CHEMBL4683',
 'CHEMBL4685',
 'CHEMBL4687',
 'CHEMBL4696',
 'CHEMBL4698',
 'CHEMBL4699',
 'CHEMBL4722',
 'CHEMBL4761',
 'CHEMBL4768',
 'CHEMBL4777',
 'CHEMBL4779',
 'CHEMBL4780',
 'CHEMBL4789',
 'CHEMBL4792',
 'CHEMBL4793',
 'CHEMBL4794',
 'CHEMBL4801',
 'CHEMBL4802',
 'CHEMBL4803',
 'CHEMBL4804',
 'CHEMBL4805',
 'CHEMBL4816',
 'CHEMBL4822',
 'CHEMBL4828',
 'CHEMBL4829',
 'CHEMBL4835',
 'CHEMBL4860',
 'CHEMBL4893',
 'CHEMBL4895',
 'CHEMBL4899',
 'CHEMBL4908',
 'CHEMBL4919',
 'CHEMBL4975',
 'CHEMBL4979',
 'CHEMBL4980',
 'CHEMBL5011',
 'CHEMBL5017',
 'CHEMBL5023',
 'CHEMBL5024',
 'CHEMBL5036',
 'CHEMBL5067',
 'CHEMBL5071',
 'CHEMBL5076',
 'CHEMBL5077',
 'CHEMBL5080',
 'CHEMBL5102',
 'CHEMBL5103',
 'CHEMBL5112',
 'CHEMBL5113',
 'CHEMBL5122',
 'CHEMBL5131',
 'CHEMBL5136',
 'CHEMBL5137',
 'CHEMBL5141',
 'CHEMBL5145',
 'CHEMBL5147',
 'CHEMBL5160',
 'CHEMBL5192',
 'CHEMBL5203',
 'CHEMBL5205',
 'CHEMBL5247',
 'CHEMBL5251',
 'CHEMBL5282',
 'CHEMBL5314',
 'CHEMBL5328',
 'CHEMBL5331',
 'CHEMBL5353',
 'CHEMBL5373',
 'CHEMBL5375',
 'CHEMBL5387',
 'CHEMBL5393',
 'CHEMBL5407',
 'CHEMBL5409',
 'CHEMBL5413',
 'CHEMBL5414',
 'CHEMBL5424',
 'CHEMBL5441',
 'CHEMBL5443',
 'CHEMBL5445',
 'CHEMBL5451',
 'CHEMBL5457',
 'CHEMBL5462',
 'CHEMBL5471',
 'CHEMBL5485',
 'CHEMBL5491',
 'CHEMBL5508',
 'CHEMBL5522',
 'CHEMBL5543',
 'CHEMBL5555',
 'CHEMBL5570',
 'CHEMBL5582',
 'CHEMBL5631',
 'CHEMBL5645',
 'CHEMBL5652',
 'CHEMBL5658',
 'CHEMBL5669',
 'CHEMBL5697',
 'CHEMBL5704',
 'CHEMBL5736',
 'CHEMBL5747',
 'CHEMBL5763',
 'CHEMBL5769',
 'CHEMBL5800',
 'CHEMBL5847',
 'CHEMBL5879',
 'CHEMBL5932',
 'CHEMBL5966',
 'CHEMBL5971',
 'CHEMBL6007',
 'CHEMBL6009',
 'CHEMBL6080',
 'CHEMBL6084',
 'CHEMBL6136',
 'CHEMBL6137',
 'CHEMBL6140',
 'CHEMBL6141',
 'CHEMBL6145',
 'CHEMBL6154',
 'CHEMBL6164',
 'CHEMBL6166',
 'CHEMBL6184']

In [28]:
train.tasks

array(['CHEMBL1075051', 'CHEMBL1075104', 'CHEMBL1075145', 'CHEMBL1075189',
       'CHEMBL1075228', 'CHEMBL1075284', 'CHEMBL1075319', 'CHEMBL1163101',
       'CHEMBL1163116', 'CHEMBL1163125', 'CHEMBL1255149', 'CHEMBL1255150',
       'CHEMBL1293255', 'CHEMBL1293289', 'CHEMBL1293292', 'CHEMBL1741186',
       'CHEMBL1741195', 'CHEMBL1744525', 'CHEMBL1764940', 'CHEMBL1781',
       'CHEMBL1781862', 'CHEMBL1782', 'CHEMBL1784', 'CHEMBL1790',
       'CHEMBL1792', 'CHEMBL1795101', 'CHEMBL1795126', 'CHEMBL1800',
       'CHEMBL1801', 'CHEMBL1804', 'CHEMBL1806', 'CHEMBL1811',
       'CHEMBL1821', 'CHEMBL1822', 'CHEMBL1824', 'CHEMBL1825',
       'CHEMBL1827', 'CHEMBL1829', 'CHEMBL1833', 'CHEMBL1836',
       'CHEMBL1844', 'CHEMBL1849', 'CHEMBL1850', 'CHEMBL1853',
       'CHEMBL1855', 'CHEMBL1856', 'CHEMBL1860', 'CHEMBL1862',
       'CHEMBL1865', 'CHEMBL1867', 'CHEMBL1868', 'CHEMBL1871',
       'CHEMBL1873', 'CHEMBL1875', 'CHEMBL1878', 'CHEMBL1881',
       'CHEMBL1889', 'CHEMBL1892', 'CHEMBL1898', 'CHEMBL1899',
       'CHEMBL1900', 'CHEMBL1901', 'CHEMBL1902', 'CHEMBL1906',
       'CHEMBL1907', 'CHEMBL1908', 'CHEMBL1913', 'CHEMBL1914',
       'CHEMBL1916', 'CHEMBL1917', 'CHEMBL1919', 'CHEMBL1921',
       'CHEMBL1921666', 'CHEMBL1926', 'CHEMBL1936', 'CHEMBL1937',
       'CHEMBL1941', 'CHEMBL1942', 'CHEMBL1944', 'CHEMBL1945',
       'CHEMBL1946', 'CHEMBL1947', 'CHEMBL1949', 'CHEMBL1951',
       'CHEMBL1952', 'CHEMBL1955', 'CHEMBL1957', 'CHEMBL1966',
       'CHEMBL1968', 'CHEMBL1974', 'CHEMBL1977', 'CHEMBL1978',
       'CHEMBL1980', 'CHEMBL1981', 'CHEMBL1983', 'CHEMBL1985',
       'CHEMBL1991', 'CHEMBL1994', 'CHEMBL1995', 'CHEMBL1997',
       'CHEMBL2000', 'CHEMBL2001', 'CHEMBL2002', 'CHEMBL2007',
       'CHEMBL2014', 'CHEMBL2016', 'CHEMBL202', 'CHEMBL2027',
       'CHEMBL2028', 'CHEMBL203', 'CHEMBL2034', 'CHEMBL2035',
       'CHEMBL2039', 'CHEMBL204', 'CHEMBL2041', 'CHEMBL2047',
       'CHEMBL2049', 'CHEMBL205', 'CHEMBL2056', 'CHEMBL206', 'CHEMBL2061',
       'CHEMBL2069', 'CHEMBL208', 'CHEMBL2083', 'CHEMBL2085', 'CHEMBL209',
       'CHEMBL210', 'CHEMBL2107', 'CHEMBL2108', 'CHEMBL211', 'CHEMBL213',
       'CHEMBL214', 'CHEMBL2146302', 'CHEMBL2147', 'CHEMBL2148',
       'CHEMBL215', 'CHEMBL216', 'CHEMBL217', 'CHEMBL2179', 'CHEMBL218',
       'CHEMBL2185', 'CHEMBL219', 'CHEMBL220', 'CHEMBL2207', 'CHEMBL2208',
       'CHEMBL221', 'CHEMBL222', 'CHEMBL223', 'CHEMBL224', 'CHEMBL2243',
       'CHEMBL225', 'CHEMBL226', 'CHEMBL2265', 'CHEMBL227', 'CHEMBL2274',
       'CHEMBL2276', 'CHEMBL228', 'CHEMBL2285', 'CHEMBL2288', 'CHEMBL229',
       'CHEMBL2292', 'CHEMBL230', 'CHEMBL2304402', 'CHEMBL2304404',
       'CHEMBL231', 'CHEMBL2318', 'CHEMBL232', 'CHEMBL2326', 'CHEMBL2327',
       'CHEMBL2329', 'CHEMBL233', 'CHEMBL2334', 'CHEMBL2335',
       'CHEMBL2337', 'CHEMBL234', 'CHEMBL2345', 'CHEMBL235', 'CHEMBL236',
       'CHEMBL2361', 'CHEMBL2363', 'CHEMBL2366456', 'CHEMBL2366505',
       'CHEMBL2366512', 'CHEMBL2366516', 'CHEMBL2366517', 'CHEMBL237',
       'CHEMBL2373', 'CHEMBL238', 'CHEMBL239', 'CHEMBL2391', 'CHEMBL2397',
       'CHEMBL240', 'CHEMBL2409', 'CHEMBL241', 'CHEMBL2413', 'CHEMBL2414',
       'CHEMBL242', 'CHEMBL2425', 'CHEMBL243', 'CHEMBL2431', 'CHEMBL2434',
       'CHEMBL244', 'CHEMBL2447', 'CHEMBL245', 'CHEMBL246', 'CHEMBL2461',
       'CHEMBL247', 'CHEMBL2470', 'CHEMBL2474', 'CHEMBL248', 'CHEMBL2487',
       'CHEMBL2488', 'CHEMBL2489', 'CHEMBL249', 'CHEMBL2492',
       'CHEMBL2499', 'CHEMBL251', 'CHEMBL252', 'CHEMBL2525', 'CHEMBL2527',
       'CHEMBL253', 'CHEMBL2534', 'CHEMBL2536', 'CHEMBL254', 'CHEMBL255',
       'CHEMBL256', 'CHEMBL2563', 'CHEMBL2564', 'CHEMBL2567',
       'CHEMBL2568', 'CHEMBL2575', 'CHEMBL258', 'CHEMBL2581', 'CHEMBL259',
       'CHEMBL2590', 'CHEMBL2599', 'CHEMBL260', 'CHEMBL261', 'CHEMBL2611',
       'CHEMBL2617', 'CHEMBL262', 'CHEMBL2622', 'CHEMBL2637', 'CHEMBL264',
       'CHEMBL265', 'CHEMBL2652', 'CHEMBL2664', 'CHEMBL267', 'CHEMBL268',
       'CHEMBL269', 'CHEMBL2693', 'CHEMBL2695', 'CHEMBL270', 'CHEMBL2716',
       'CHEMBL2722', 'CHEMBL273', 'CHEMBL2730', 'CHEMBL2736', 'CHEMBL274',
       'CHEMBL2742', 'CHEMBL2749', 'CHEMBL275', 'CHEMBL2756', 'CHEMBL276',
       'CHEMBL2778', 'CHEMBL278', 'CHEMBL2781', 'CHEMBL2782',
       'CHEMBL2789', 'CHEMBL279', 'CHEMBL280', 'CHEMBL2803', 'CHEMBL2808',
       'CHEMBL2815', 'CHEMBL2820', 'CHEMBL2828', 'CHEMBL283',
       'CHEMBL2830', 'CHEMBL2835', 'CHEMBL284', 'CHEMBL2842', 'CHEMBL285',
       'CHEMBL2851', 'CHEMBL2858', 'CHEMBL286', 'CHEMBL2868', 'CHEMBL287',
       'CHEMBL2871', 'CHEMBL288', 'CHEMBL2882', 'CHEMBL2885',
       'CHEMBL2902', 'CHEMBL2903', 'CHEMBL2916', 'CHEMBL2949',
       'CHEMBL2954', 'CHEMBL2959', 'CHEMBL2971', 'CHEMBL2973',
       'CHEMBL2978', 'CHEMBL298', 'CHEMBL299', 'CHEMBL2993', 'CHEMBL2996',
       'CHEMBL2998', 'CHEMBL301', 'CHEMBL3012', 'CHEMBL3018', 'CHEMBL302',
       'CHEMBL3024', 'CHEMBL3025', 'CHEMBL3037', 'CHEMBL304',
       'CHEMBL3045', 'CHEMBL3048', 'CHEMBL3060', 'CHEMBL3066',
       'CHEMBL3067', 'CHEMBL3072', 'CHEMBL308', 'CHEMBL3081',
       'CHEMBL3085613', 'CHEMBL309', 'CHEMBL3100', 'CHEMBL3105',
       'CHEMBL3106', 'CHEMBL311', 'CHEMBL3114', 'CHEMBL3116', 'CHEMBL312',
       'CHEMBL313', 'CHEMBL3130', 'CHEMBL3138', 'CHEMBL3142',
       'CHEMBL3145', 'CHEMBL3155', 'CHEMBL3157', 'CHEMBL3166',
       'CHEMBL318', 'CHEMBL3180', 'CHEMBL3181', 'CHEMBL319', 'CHEMBL3192',
       'CHEMBL3199', 'CHEMBL3202', 'CHEMBL321', 'CHEMBL322', 'CHEMBL3222',
       'CHEMBL3223', 'CHEMBL3227', 'CHEMBL3229', 'CHEMBL3230',
       'CHEMBL3231', 'CHEMBL324', 'CHEMBL3242', 'CHEMBL3247', 'CHEMBL325',
       'CHEMBL3254', 'CHEMBL326', 'CHEMBL3267', 'CHEMBL3286', 'CHEMBL330',
       'CHEMBL3305', 'CHEMBL331', 'CHEMBL3310', 'CHEMBL3314',
       'CHEMBL3318', 'CHEMBL332', 'CHEMBL333', 'CHEMBL3332', 'CHEMBL335',
       'CHEMBL3351', 'CHEMBL3358', 'CHEMBL3360', 'CHEMBL3361',
       'CHEMBL3371', 'CHEMBL3374', 'CHEMBL338', 'CHEMBL339',
       'CHEMBL3399910', 'CHEMBL340', 'CHEMBL3403', 'CHEMBL3419',
       'CHEMBL3426', 'CHEMBL3437', 'CHEMBL3438', 'CHEMBL344',
       'CHEMBL3464', 'CHEMBL3468', 'CHEMBL3471', 'CHEMBL3473',
       'CHEMBL3474', 'CHEMBL3476', 'CHEMBL3486', 'CHEMBL3501',
       'CHEMBL3510', 'CHEMBL3513', 'CHEMBL3522', 'CHEMBL3524',
       'CHEMBL3535', 'CHEMBL3553', 'CHEMBL3559', 'CHEMBL3563',
       'CHEMBL3568', 'CHEMBL3571', 'CHEMBL3572', 'CHEMBL3582',
       'CHEMBL3587', 'CHEMBL3589', 'CHEMBL3590', 'CHEMBL3594',
       'CHEMBL3602', 'CHEMBL3614', 'CHEMBL3623', 'CHEMBL3629',
       'CHEMBL3638338', 'CHEMBL3649', 'CHEMBL3650', 'CHEMBL3687',
       'CHEMBL3691', 'CHEMBL3699', 'CHEMBL3706', 'CHEMBL3710',
       'CHEMBL3717', 'CHEMBL3729', 'CHEMBL3746', 'CHEMBL3759',
       'CHEMBL3764', 'CHEMBL3766', 'CHEMBL3768', 'CHEMBL3769',
       'CHEMBL3772', 'CHEMBL3775', 'CHEMBL3776', 'CHEMBL3778',
       'CHEMBL3785', 'CHEMBL3788', 'CHEMBL3795', 'CHEMBL3798',
       'CHEMBL3802', 'CHEMBL3807', 'CHEMBL3815', 'CHEMBL3816',
       'CHEMBL3820', 'CHEMBL3833', 'CHEMBL3836', 'CHEMBL3837',
       'CHEMBL3864', 'CHEMBL3868', 'CHEMBL3869', 'CHEMBL3880',
       'CHEMBL3884', 'CHEMBL3891', 'CHEMBL3892', 'CHEMBL3910',
       'CHEMBL3912', 'CHEMBL3920', 'CHEMBL3922', 'CHEMBL3942',
       'CHEMBL3943', 'CHEMBL3948', 'CHEMBL3952', 'CHEMBL3959',
       'CHEMBL3969', 'CHEMBL3974', 'CHEMBL3975', 'CHEMBL3976',
       'CHEMBL3979', 'CHEMBL3983', 'CHEMBL3991', 'CHEMBL3996',
       'CHEMBL4005', 'CHEMBL4015', 'CHEMBL4016', 'CHEMBL4018',
       'CHEMBL4026', 'CHEMBL4029', 'CHEMBL4040', 'CHEMBL4051',
       'CHEMBL4068', 'CHEMBL4072', 'CHEMBL4073', 'CHEMBL4074',
       'CHEMBL4077', 'CHEMBL4078', 'CHEMBL4080', 'CHEMBL4093',
       'CHEMBL4102', 'CHEMBL4111', 'CHEMBL4123', 'CHEMBL4124',
       'CHEMBL4128', 'CHEMBL4132', 'CHEMBL4140', 'CHEMBL4142',
       'CHEMBL4145', 'CHEMBL4150', 'CHEMBL4153', 'CHEMBL4161',
       'CHEMBL4179', 'CHEMBL4188', 'CHEMBL4191', 'CHEMBL4198',
       'CHEMBL4203', 'CHEMBL4204', 'CHEMBL4224', 'CHEMBL4234',
       'CHEMBL4235', 'CHEMBL4247', 'CHEMBL4261', 'CHEMBL4282',
       'CHEMBL4296', 'CHEMBL4302', 'CHEMBL4303', 'CHEMBL4306',
       'CHEMBL4308', 'CHEMBL4315', 'CHEMBL4321', 'CHEMBL4333',
       'CHEMBL4336', 'CHEMBL4338', 'CHEMBL4354', 'CHEMBL4358',
       'CHEMBL4361', 'CHEMBL4372', 'CHEMBL4393', 'CHEMBL4394',
       'CHEMBL4409', 'CHEMBL4414', 'CHEMBL4422', 'CHEMBL4427',
       'CHEMBL4429', 'CHEMBL4430', 'CHEMBL4439', 'CHEMBL4441',
       'CHEMBL4462', 'CHEMBL4465', 'CHEMBL4471', 'CHEMBL4477',
       'CHEMBL4478', 'CHEMBL4481', 'CHEMBL4482', 'CHEMBL4501',
       'CHEMBL4506', 'CHEMBL4508', 'CHEMBL4523', 'CHEMBL4550',
       'CHEMBL4552', 'CHEMBL4561', 'CHEMBL4581', 'CHEMBL4586',
       'CHEMBL4588', 'CHEMBL4599', 'CHEMBL4600', 'CHEMBL4608',
       'CHEMBL4616', 'CHEMBL4617', 'CHEMBL4618', 'CHEMBL4625',
       'CHEMBL4630', 'CHEMBL4633', 'CHEMBL4641', 'CHEMBL4644',
       'CHEMBL4649', 'CHEMBL4652', 'CHEMBL4653', 'CHEMBL4657',
       'CHEMBL4660', 'CHEMBL4662', 'CHEMBL4681', 'CHEMBL4683',
       'CHEMBL4685', 'CHEMBL4687', 'CHEMBL4696', 'CHEMBL4698',
       'CHEMBL4699', 'CHEMBL4722', 'CHEMBL4761', 'CHEMBL4768',
       'CHEMBL4777', 'CHEMBL4779', 'CHEMBL4780', 'CHEMBL4789',
       'CHEMBL4792', 'CHEMBL4793', 'CHEMBL4794', 'CHEMBL4801',
       'CHEMBL4802', 'CHEMBL4803', 'CHEMBL4804', 'CHEMBL4805',
       'CHEMBL4816', 'CHEMBL4822', 'CHEMBL4828', 'CHEMBL4829',
       'CHEMBL4835', 'CHEMBL4860', 'CHEMBL4893', 'CHEMBL4895',
       'CHEMBL4899', 'CHEMBL4908', 'CHEMBL4919', 'CHEMBL4975',
       'CHEMBL4979', 'CHEMBL4980', 'CHEMBL5011', 'CHEMBL5017',
       'CHEMBL5023', 'CHEMBL5024', 'CHEMBL5036', 'CHEMBL5067',
       'CHEMBL5071', 'CHEMBL5076', 'CHEMBL5077', 'CHEMBL5080',
       'CHEMBL5102', 'CHEMBL5103', 'CHEMBL5112', 'CHEMBL5113',
       'CHEMBL5122', 'CHEMBL5131', 'CHEMBL5136', 'CHEMBL5137',
       'CHEMBL5141', 'CHEMBL5145', 'CHEMBL5147', 'CHEMBL5160',
       'CHEMBL5192', 'CHEMBL5203', 'CHEMBL5205', 'CHEMBL5247',
       'CHEMBL5251', 'CHEMBL5282', 'CHEMBL5314', 'CHEMBL5328',
       'CHEMBL5331', 'CHEMBL5353', 'CHEMBL5373', 'CHEMBL5375',
       'CHEMBL5387', 'CHEMBL5393', 'CHEMBL5407', 'CHEMBL5409',
       'CHEMBL5413', 'CHEMBL5414', 'CHEMBL5424', 'CHEMBL5441',
       'CHEMBL5443', 'CHEMBL5445', 'CHEMBL5451', 'CHEMBL5457',
       'CHEMBL5462', 'CHEMBL5471', 'CHEMBL5485', 'CHEMBL5491',
       'CHEMBL5508', 'CHEMBL5522', 'CHEMBL5543', 'CHEMBL5555',
       'CHEMBL5570', 'CHEMBL5582', 'CHEMBL5631', 'CHEMBL5645',
       'CHEMBL5652', 'CHEMBL5658', 'CHEMBL5669', 'CHEMBL5697',
       'CHEMBL5704', 'CHEMBL5736', 'CHEMBL5747', 'CHEMBL5763',
       'CHEMBL5769', 'CHEMBL5800', 'CHEMBL5847', 'CHEMBL5879',
       'CHEMBL5932', 'CHEMBL5966', 'CHEMBL5971', 'CHEMBL6007',
       'CHEMBL6009', 'CHEMBL6080', 'CHEMBL6084', 'CHEMBL6136',
       'CHEMBL6137', 'CHEMBL6140', 'CHEMBL6141', 'CHEMBL6145',
       'CHEMBL6154', 'CHEMBL6164', 'CHEMBL6166', 'CHEMBL6184'],
      dtype='<U13')

In [56]:
import json

# Pick the first sample that has at least one observed task, so y is a real measurement.
has_observation = (train.w != 0).any(axis=1)
candidates = np.flatnonzero(has_observation)
if candidates.size == 0:
    raise RuntimeError("No sample in train has any observed task; check the loader output.")
i = int(candidates[0])

x_vec = train.X[i]
w_row = train.w[i]
y_row = train.y[i]

record = {
    "smiles": str(train.ids[i]),
    "X":      x_vec.astype(int).tolist(),   # 1024-length ECFP bit vector
}

# One entry per observed task: key = task name, value = y for that task.
observed_task_indices = np.flatnonzero(w_row != 0)
for t_idx in observed_task_indices:
    record[tasks[int(t_idx)]] = float(y_row[t_idx])

record_json = json.dumps(record)
print(f"JSON size: {len(record_json):,} chars")

JSON size: 3,297 chars

In [59]:
from pprint import pprint 
pprint(record)

{'CHEMBL214': 5.182933408873236,
 'CHEMBL217': 3.91905576465042,
 'CHEMBL224': 5.317881355992391,
 'CHEMBL225': 6.245883257904363,
 'CHEMBL234': 6.222473937546522,
 'X': [0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       1,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       1,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       1,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0],
 'smiles': 'Cc1cccc(N2CCN(CCCCNC(=O)c3oc4ccccc4c3)CC2)c1C'}

In [ ]:
# Optionally persist to disk.
with open("sample0.json", "w") as f:
    json.dump(record, f)

## Translate task IDs → biomolecular targets

DeepChem's ChEMBL task names are ChEMBL **target** identifiers (e.g. `CHEMBL204`).
We use the official `chembl_webresource_client` (batches + local cache) to translate
each task into:

- `pref_name` — human-readable name (e.g. *Prothrombin*, *Dopamine D2 receptor*)
- `target_type` — coarse bucket (`SINGLE PROTEIN`, `PROTEIN COMPLEX`, `CELL-LINE`, `ORGANISM`, …)
- `organism`
- `uniprot` — accession(s) for cross-reference
- Protein-classification hierarchy `l1 … l5` — the most interpretable grouping

Install with `uv add chembl_webresource_client` if it isn't already.

In [38]:
from chembl_webresource_client.new_client import new_client

def translate_tasks(task_ids: list[str]) -> pd.DataFrame:
    """Batch-translate ChEMBL target IDs into names + protein-class hierarchy."""
    task_ids = list(task_ids)

    # 1. Batch fetch target metadata + their components.
    targets = list(new_client.target.filter(target_chembl_id__in=task_ids))
    target_by_id = {t["target_chembl_id"]: t for t in targets}

    all_component_ids = {
        c["component_id"]
        for t in targets
        for c in t.get("target_components", [])
    }

    # 2. Batch fetch component detail (this is where protein_classifications live).
    components = list(
        new_client.target_component.filter(component_id__in=list(all_component_ids))
    )
    comp_by_id = {c["component_id"]: c for c in components}

    all_class_ids = {
        pc["protein_classification_id"]
        for c in components
        for pc in c.get("protein_classifications", [])
    }

    # 3. Batch fetch the classification nodes; protein_class_desc has the full L1..Ln lineage.
    class_nodes = list(
        new_client.protein_classification.filter(protein_class_id__in=list(all_class_ids))
    )
    class_by_id = {c["protein_class_id"]: c for c in class_nodes}

    rows = []
    for tid in task_ids:
        t = target_by_id.get(tid)
        row = {
            "task":     tid,
            "name":     None,
            "type":     None,
            "organism": None,
            "uniprot":  None,
            "l1": None, "l2": None, "l3": None, "l4": None, "l5": None,
            "class_path": None,
        }
        if t is None:
            rows.append(row)
            continue

        row["name"]     = t.get("pref_name")
        row["type"]     = t.get("target_type")
        row["organism"] = t.get("organism")

        # First protein component gets to define uniprot + protein class.
        for comp_ref in t.get("target_components", []):
            comp = comp_by_id.get(comp_ref["component_id"], {})
            if comp.get("component_type") != "PROTEIN":
                continue
            row["uniprot"] = comp.get("accession")
            pcs = comp.get("protein_classifications", [])
            if pcs:
                node = class_by_id.get(pcs[0]["protein_classification_id"], {})
                # protein_class_desc is space-separated L1..Ln in lowercase.
                levels = (node.get("protein_class_desc") or "").split()
                for i, lvl in enumerate(levels[:5], start=1):
                    row[f"l{i}"] = lvl
                row["class_path"] = " > ".join(levels) or None
            break
        rows.append(row)

    return pd.DataFrame(rows)

In [49]:
# Translate every observed task for sample i.
observed_task_ids = [tasks[int(t)] for t in observed_task_indices]
df_targets = translate_tasks(observed_task_ids)

## Interpretable groupings

- **`type`** — coarsest: `SINGLE PROTEIN`, `PROTEIN COMPLEX`, `CELL-LINE`, `ORGANISM`, …
- **`l1`** — biology top-level: `enzyme`, `membrane receptor`, `transcription factor`, `ion channel`, `transporter`, `epigenetic regulator`, …
- **`l2`** — the useful working level: `enzyme > kinase / protease / oxidoreductase`, `membrane receptor > family a g protein-coupled receptor`, …

In [50]:
df_targets.groupby(["type", "l1"], dropna=False).agg(
    n_tasks=("task", "count"),
    examples=("name", lambda s: list(s)[:3]),
)

,,n_tasks,examples
type,l1,,
SINGLE PROTEIN,membrane,5,"[5-hydroxytryptamine receptor 1A, D(2) dopamin..."

In [47]:
# Larger slice — useful for understanding the whole benchmark, not just one sample.
# Bump the slice size once you're comfortable with the request time.
sample_ids = list(tasks[:200])
df_all = translate_tasks(sample_ids)

df_all.groupby(["l1", "l2"], dropna=False).size().sort_values(ascending=False).head(30)

l1             l2
membrane       receptor             65
enzyme         kinase               25
               reductase            20
               protease             19
transcription  factor               14
enzyme         NaN                   9
ion            channel               7
enzyme         isomerase             6
epigenetic     regulator             5
transporter    electrochemical       5
enzyme         hydrolase             5
               transferase           4
               phosphodiesterase     4
auxiliary      transport             2
enzyme         lyase                 2
               cytochrome            2
cytosolic      other                 1
membrane       other                 1
secreted       NaN                   1
enzyme         ligase                1
transporter    ntpase                1
unclassified   NaN                   1
dtype: int64

In [52]:
df_all.groupby(["l1", "l2"], dropna=False).size().sort_values(ascending=False)

l1             l2
membrane       receptor             65
enzyme         kinase               25
               reductase            20
               protease             19
transcription  factor               14
enzyme         NaN                   9
ion            channel               7
enzyme         isomerase             6
epigenetic     regulator             5
transporter    electrochemical       5
enzyme         hydrolase             5
               transferase           4
               phosphodiesterase     4
auxiliary      transport             2
enzyme         lyase                 2
               cytochrome            2
cytosolic      other                 1
membrane       other                 1
secreted       NaN                   1
enzyme         ligase                1
transporter    ntpase                1
unclassified   NaN                   1
dtype: int64